name: i_beer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0
  equatable: ^2.0.3
  dio: ^4.0.4
  dartz: ^0.10.1
  connectivity_plus: ^2.2.0
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: any

flutter:
  uses-material-design: true

  #https://itnext.io/mvvm-in-flutter-using-providers-409c3c7e654